import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="flex">
            <Navbar />
          </div>
          <div className="ml-64">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html >
  );
}
